# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccountmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordManager',
            new_name='WebAccountManager',
        ),
    ]
