# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('req_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('currency', models.CharField(choices=[('inr', 'inr'), ('dollar', 'dollar')], max_length=10, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_purchased', models.BooleanField(default=False)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Grocery')),
            ],
        ),
    ]
