# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='currency',
            field=models.CharField(choices=[('inr', 'inr'), ('dollar', 'dollar')], default='inr', max_length=10, unique=True),
        ),
    ]
