# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20180801_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
