# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20180801_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='req_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
