# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180721_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
