# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtube_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='youtube',
            name='downloaded_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtube',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='youtube',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
    ]
